name: Automate Video Generation

on:
  schedule:
    - cron: '0 */2 * * *'  # Runs every 2 hours
  workflow_dispatch:  # Allows manual triggering

jobs:
  automate-video:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Docker
        run: |
          docker build -t reddit-video-bot .

      - name: Run Automation Script
        run: |
          docker run \
            -v ${{ github.workspace }}/results:/app/results \
            -v ${{ github.workspace }}/logs:/app/logs \
            -e REDDIT_CLIENT_ID=${{ secrets.REDDIT_CLIENT_ID }} \
            -e REDDIT_SECRET=${{ secrets.REDDIT_SECRET }} \
            -e REDDIT_USERNAME=${{ secrets.REDDIT_USERNAME }} \
            -e REDDIT_PASSWORD=${{ secrets.REDDIT_PASSWORD }} \
            -e INSTAGRAM_USERNAME=${{ secrets.INSTAGRAM_USERNAME }} \
            -e INSTAGRAM_PASSWORD=${{ secrets.INSTAGRAM_PASSWORD }} \
            -e YOUTUBE_CLIENT_SECRET_JSON=${{ secrets.YOUTUBE_CLIENT_SECRET_JSON }} \
            reddit-video-bot bash Automator.sh