name: FullyAutomatedRedditVideoMakerBot

on:
  schedule:
    - cron: '0 */2 * * *'  # Runs every 2 hours
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install OS-level dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y --no-install-recommends \
            gcc \
            g++ \
            libffi-dev \
            libssl-dev \
            libxml2-dev \
            libxslt-dev \
            zlib1g-dev && \
          sudo apt-get clean && sudo rm -rf /var/lib/apt/lists/*

      - name: Install Python dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install --prefer-binary -r requirements.txt

      - name: Configure YouTube Credentials
        run: |
          mkdir -p uploaders
          echo "${{ secrets.YOUTUBE_CLIENT_SECRET_JSON }}" | base64 --decode > uploaders/client_secret.json

      - name: Run Bot
        env:
          REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          REDDIT_SECRET: ${{ secrets.REDDIT_SECRET }}
          REDDIT_USERNAME: ${{ secrets.REDDIT_USERNAME }}
          REDDIT_PASSWORD: ${{ secrets.REDDIT_PASSWORD }}
          INSTAGRAM_USERNAME: ${{ secrets.INSTAGRAM_USERNAME }}
          INSTAGRAM_PASSWORD: ${{ secrets.INSTAGRAM_PASSWORD }}
        run: |
          source venv/bin/activate
          python main.py